apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: gitops-cp-bas
spec:
  encryptedData:
    db_password: AgCYFyTZcn59DbEz/N70W9MCz/oUqs1pR/mh1ymZESQEN6/LPbaVmZ4RzU7OHfwRWtgAfx3hbGQU7Hb6LatAhouFzkE+I/2wtVNX5mAyNL75TueBxZCKwNpDz4LlFdcGCtgcBPAUYQxF/UTan3leFwRN4dalg2HNRS1HdEpMKBRWZkeKnmQQCPHJ/Wi750viqnzvHcLQwpv2qr8ryJznA41Mbwm9sRcr1qJ0tPBPjSyB89OozyiND7E0pBtiStGqhF8+XynTXf86UofsynnNNTfM7aGAtWdPxHAC5LxzHgtyAtcCoxadB1jgHz9+i3pxK4VtJfwwv6SVDUEdYGF6QjHy4+NRsYcM8yO9N2llsJTY0AZSHqx/eH4d7it4rNU88YXYNTwIknkkX9Jg3a3AP4HpiusZRv0v5CejVCER5tEUisfLHDUQ7+WeSHbJCqO4iGbWGgY2jSR2UhUMbJ/ILU4E4tO+59Toj7Grdg5qTsrb8h8kCL5u27MHbjMRWkMTUQqn+uxuPZD3vtEHgI5B9398WnzjUSans5/KLtpJL7cThXTjFCPxEIzjNknecVLAJ4NSAPgZXY9AZxff1qUE7OnWXrYDEfFPh5BqLPNs1UJkdHjhUwLPSuCtHZJtgdDy5QqzskLL404tNuTTDrvjWlSnkyCBvc3Nkwob9c0Mgc54g2lGz8qU3fHiLYACEDnXvLw70WSFZeSvdHUM
    db_username: AgA+cOLed+Tj+cDFINjMPqB1hZfPPmrAxJwY2kC5DSb7eD7CetKVkhLNfRiNohEVep2UOas2/uFvBVhcVp0PZfdOyG01pkMa23Gha0+k7S4g9VsH0oj0grAgEM3dAOXgKKuLe3VciAyuIfmbbbLmPFivFGVOCjrirjlBrbj9hgNpjS+PR2mo+90UmB17mPLVJ2ElQV67Zn+GDVvcK/IKb5RmLb/dP7dZwRz/XpdtPJNQE+1hR0j6jUkum+1QCTje7ovhLhECgBvBV4iouB9vqmf8EEPObTlgrbx7Ih9J13sOhZAjqcwhRP+gW4DxIEDIZCX1aXNgOelAagi5gkgW6C1u9UhdX1zeO4r0fkz19iJMe7l9o7TxfFjlE6NaKgZKQkWKpxNLc++u9Tgjv8s9sVD3c4wDjijvoT5osAE5bdVB0QbfIgVXGWGhbORVBeUSC015KzqmocZRcELjPMjDbj+2CixxyEu+9eHkTfG2ttVRVKUegs+dhW3BJFmYN/TYlW3PrgnuzfK+VqTjzvZO1z2BhZzL2M/XW4c4qK34thYvaS20WVmg2wxhlA3ndiJo6FkHY+I0XUcxvmtZbfAUGVksoWGBnQNhD9E1T5UmFF+O/tygG6oUX2d2O4+av6uxjQ/Xnd0S6iZOmkiFkMuvClhZC0VXsLqxGIBhz72t15XoTnKyxJ9ZTg85WpWG8RnDxf4FrbG7DXQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: gitops-cp-bas

