apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: gitops-cp-bas
spec:
  encryptedData:
    db_password: AgAfrDntvNVA/h17c4cPFOOCtjm6Rut7BZfXvdr4CFFF6JaRzBn7ZPKIcXou8ZwW2E8PUbB7FqAj+2sTlrOC3iKJxe50O7VckXqQ6y+HfA5M3b0yf9r/rjn1xrl48KA6UPF7Oar/9wTn6L/tcpZOLbSrvo0Do20hZ7u3p6azKeaQaSebb8RUSHqKxru8UR8SbFrqk0FskE3f7KM6Cybr93OR8gyXT0eBfY2Sot4VxaG07OYV3QUjbpCaKXGhaJoaO9iGMEO9gOUkRspmq8NRomYswP+PQzCc2fbtNNJrNBZxM8RDlv9HMaucjBl7n9e84rwphrEJEG31Szs84hrA5yKwHIrEFJYp/SyxPEhorN3DGp2sBPW3w0Nlep6K1w8mJb/P5xmGb0bWn61ndpudz8MX7k+EYZq9Nc6qhTUI7bhWbf/ejkN6oVrU1aLCaLlJFBPvWysJpGYNdJ3tTDhWIsMGdJwAB9cZ4BYUDfFPtiUEJKzUy8UDq3BkSZ6ftYXE0/2VEI6qVxjwDVtLJAmHUNj6FEBEGEtagLI/TJ8RS+rBB1eLuAFg95hQDqQf0e+Q8bzLdg941kDF007b9NQ2A4deQj3oLvn7luPMj++O7UaIJzF5LWXHNxLnmgsOxEEsXZUUh4WASWptbv30C1XSOGq5VOk81axEjPTaRJWsnh6D4N4t2+jGnxwPnJ+DGtjaNBkGsFF9PC9jv+6+
    db_username: AgBFGKNFapVMBKonV7AArTg2s4tzj22HsTeconvkHqrZzgXHQoGrbnfGvRzkUEts94qMSfBn+lY7XNQ+XA8jR44cLST2yA1jiro733IdLymFKQv6M6PUuUsXWHqggLBgc98T9FF9QGwSisKpih9ANsBWxXcOSsg1BAZBmyQKXoqtPubkeDBV5K71KKSLCUpF7tnNVM60Cxu+Q2mP6PVlJdNVIKQirbf8V3VKXuAW5rmFCZybPf5+N3l0zFTqJLKIvAlGjwnIqLxHE/9bGdFzgHoI1BoATyjCAO2cupdNBTPpimjZsfdXCkOR2rJL2VYJCEZ2zY2SKARiAYTfv0KLBTh5w5LMNdQ7bqdbIDyPpwkmsWgAwK7N/FnJhn/glnP72sJdVA6TR4Sl2k/jyBIn0+0D6QOCRkW4YVE54QrAmtPW1ua8rWbhoU7fzk3nnHywI9I1c2cFo9Ividv27T+w7McnjIs6sDd3tY7SwD7KDNKXkcd+qUSvRtHwdlmMbPhYoZFCJWuWkQpD9KGOTQS1BYPl1FTQZSgyIpSzz/c+BOEWvx8S6vV8WJsz9Eslu7OnHoASMXzZAj++KF96xkNSwKSgiCANHNHjvLt1X/z4r7nsG3pL5Uq6heaAVw/S2DZ/aDQcarJOSxRmFCHaklbf1eXZTT79pcaMCJXKVygBw7ZhKWJNpR1jbm8HFa/gh6v+pcqQVLtc/SI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: gitops-cp-bas

