apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: gitops-cp-bas
spec:
  encryptedData:
    db_password: AgCITm28/pA8KJYgEsXqXusL96msdVGbuslzB2G/E8aDqvq4+PV5UiPxYd294aT832d9rnUOeTDbL8ZOB1/lkSg4XzyXyxX5lkun+x+XSvS2c45XcTcX5+WCbvyaQIAZTZmse6ylk9OA3OFeh7ouJe8RhMO4L96Q6Bwi6OkaPmOHLCsdMDk83RTI4fvsrb2DrhyO1dlzN49rmvU0+flvVq7tV4Z5tdcU9IV7TpDTCvitx5bh7VVEf60rFjFBX06RDtY5527/vUPHUJHVGTkwNn4YqRKED82kl8HIJlJ9etak1NEOWQojsJtaI3Te4qow4Ow8KgjxsSxg0Ea2YkF58Aabiqvymm7hRqA3BPwzdzTbedAjVwa39IGnNa3y420XORoPQZSfiuCKivpf18w9zspQcJ9vcZS16EMIq60r78XGdae/IRw4p1vj/AgyiycnPcih+74F3zA2njZortY+OIq3FHDY1U1b7LZw1P1JPuLxj7kjJcclxzb9ZvvRjPoOkobCb+WJ5aOwK3Xvq106cnu+BHVYEmn9TpJtE2fMQLPgaKBPD+uAQ/+7HIDwksdP4oMN1h0qRGrrBunQZDRUMsILwTE1IoCtF4/JzuWLrcTBIpI70QsqMofSrJt+mA012vRnQJpGqkm6jUkoRVPmW3MXlGZCLD/P5Ez4iXceU233UUwCnGkR8IzYVvWjQBRqQ4zrXY7ZOKYyH80O
    db_username: AgANER5wZ+sgXlB0Pky8pIB+/35izFrFlu+boI56j/Ewo+tnnzr9nm0xzwLKXkPe8XjZOy/Z585hCu62ZyjH8FzpjJNdEblNZS+Orki+taGpH1Ck2sGtMif3PaY9hgxWbtJ+0ExPK1PeHBn8MRGB0y2c4SB/w8t893zI4LXN7S+rWZcV1uRbzRXfhxJLvYaOfCpPRWYz6ihp88QM+/u4yCribOp1AUAMkSU/5LuVHwXtssgZElmqFBh8KZ+uxeMJCdS4gy1Q1v+Kj5mp86PZ/8usv3API+Nsw6umY8pH+w7JhuF4Xy1arBZ3FNht3ktC6RExF9xBJit7u+8PYwtkYFuz9IMyS609TRjdROSYAvBC+q3kIyMnhgv/23nGvcyNaxUxstyyrkKrAQrT7qvqbBXio5d+gdVVTQi+SNuYyWkvYcQlA63TfYlAIUM2wnZMNkFljL6iXVRNMSWRUPoaflFcHyNHASN86LXs0NfYzyDR62e47aAM3uawYJULuwGtmqd34PHttlhpymhKcLY9DRAD5N36mfHh+87COS1xdPaYW8xeP6dS1pMbuHp1HfrkFpLor3Quyi/yai3+zfmGShYodDQ7eGlp1ccknXUwicKyWHxIDVL/y9H8K2C2CAYigynC2UuSAZhJeTvdgqzP+jfqAcJoi/kkokqZrOvXfF8qAib0bCIvlijRp1qAHINw8agO6j26Yjk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: gitops-cp-bas

