apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgAi4wJjCVo1Oidj/BFXRS6tefd0xRRMJex0h4YqhsmWdWU3tBSVZKp5BDryyzh4XlKdM+Mn0H2l3bul8E5z1/dUWxD4jcwqne8L+I/UgkWkBE4PuPMTGrEZd93dDDQEb2eBluD6+IIVk8KGdj4ilW9xwz719rjajjPCGnD8SJQCWGzmv4oRLuzfgYGiOvt6LjmBJMpd1EI/Jdw0esqtvs2A8qN6xkTXNbqhWyIoGU58MykjitRsTzpyNdnsTDrEeH1YjhvyG8ucbO1JL1N8i342Abda6NRTM6RIyRxHm+NHDzpItIcxISDAgtbYn8qTtJZLqN7Lj7mdxoVuCM0hiUhZUq8ta9w8gYWijaqdoH4EjmJTKCnDUddPCcPB+/uBSxFz1n1D8rFlZC9/Lvh0SOe8id5HeYgfsQDtIwdR8mceWUZ1EblUXz1+6JMMkF+PT5OTyZiDduovGoPgrAcIzBTaO1GFkP3u4+qWkM7WtmkGMd80TK0ExQ28kKwkJnGnW9fbcXAiF3mFZDCIbzOblNTyLEVDE/7b9vyw7oD+5SKxwuSBBH7zsIhk70oUwTAvFeDli3u85mjz6oU2JkhXS08i1l9f+wwgnUby8udTkt5HxGXJ2RJr1/RmxK244P4amgDpcscYzIWu18tATl3eGh/7kGI0G70wwJRVDwcEJmobF44WIhB9w6AP3dYou2DCT2GV9hA96oxKV3HbOdK7w048ci7FOU4tnoYdlN7bbwdPzi13e0lTdiMo10JK+twySzbYzbLkY5WQ0ys2fgQDq4mkqgq+kFo0vb0WBUzdmZdXvqg847trtF3IKNfp6v7wm2fN7aHgiH6LEKVviZBo0JVi7vP1dIvzZ5R3oO/yIS6nZuDe/MuM3XBf7MGwWvQWs6nfkEgdD59XXUD70nSr97CKtVjzf1h4jqaifEBmo/h3fPQyiD/Wn213xmD25+5E2KExm8iQlCNYMs9FSO7B9tDlC+XG6JiM8vAFljhk4/0PayUve5PM25QfG5waxGOt2NU1Xt771qcMYk1k1MXKoAOYuWzZjXLWRqYhnLvGKUnsABa/8gO+/bM7UqmUE/TFuy9fv3c/3wa+k+59nd1w8HhFGQMKzMVjvlZWA4PolhxaB/UJ0TRd0A4wQnVLZC4rt9T8l+PsX7t2xap+rqrxQWzL5/Dkue9c1hlN1AjzIGqRYbdQROnIefdMN/VqHZdyDXsf7OrAOfl15Z76a8r3lnc4yxYUy8OlbEMs9m6SojILt5pfEX1TtWy8oPpGO9hEsEBez7cFjBgflOsiarvcd8fuDJRt7G3TXYynfCjeYcDszC1YIk01kHpoYrEBeh8VBhGY
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

