apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgBp1LgEzunNe45Hz8wtHgA1L9yXhhADJaBVbrpkoNeEhHcG+5L9ehefrI2mEazjcweBVa3muyH/zDsqu2Qv420gGGL4OOnzDLcFCioUdmn5Ei3dTc7SN0xM6AKbo6k+RYq9qq+nIYdwf1L1Tp0yIrBXqQzkCe9EPpFt8Ht97vwURnx24DqUcSMt+viz1z6KSsLvZnu+sZRX2pOarxeXFwthDSpZtDzJMK3d/qh0UHO3uoKcaGciKicQ0DJ4PpAR2/TJD12Ia4zY8xWRtah8cBimpE8y17weocfrZWPf5QLT4iaCl38rhtnEysePmK7bfxfPvro2Lbk4xGYsNtP893u5O6rtDWQ9mLwiuUFw/SXZQyHp+W0EVCjMZXy/0nhpOMw3a7VbSAYB6+VaJZh4jRxuRJlH4OTmbI2J5D2Dm1rrPBGM+heegUS/61hgpZn1Ewyk7y13QrJ5IfhF5WVMVRLWK6Ki0FjSVv1MZsZ6JtjHqTgTEU7grgE8q4rSdr5atD4uQBB3a225fKiW0s3adkvTUtl0VQTJjqKtPmdBMXL6YJIzGC3wydcqKRiKZzF8LxVvua+Sxcl8DhDfJoP+U8PPY+/bzCuHoaMSN7qR26a5x1hk2iWVsLZm6xjVxKxFdXgu8884eP78oHGHs7/eG9pSBHcwCi4EpRwWUG/nkSHEigE2JLr2kqfqQcAhNuWQWy3qefp+/yBjFeIxKjAQr9R/y9lxcYQMwTvodl0AydWpdhYCbeq4fwbwCyKElYPLIOod36HdrhxFimvUCho/SSYVXJ7c7pRnSKdY9yFhEM/XwnnZ91ucnj86h+zk4RVxdf53eOd24EPzdPg8477fvjG0a5enyxGv1eTIG8qC7vknoa/tGAIpxmU6xrPDk+sYdKPzpEkDqtR72DarYcRRlCa5pR/PilW9izTlqq1JSafGJclMV3JkQpOgMnzRyYQrnAy74fE265cm/J3eVkmgrLQztCzkIohmdGf0ttmu0Hs63GynO6YNUERRZ/Oi5FpTHyKWEzGI5R3YTwKKodEb8kGV3GK0hRsTyO6wIXTz+W5bJTBTZnuOtXpuIIKhrt0XqgYq1SiaQQYQZPYqLuzBfeYGZTjRSE7lXvu9ufN5uYOQ1L5Ua+GKNr4BBUipusaro/TdwFhLXhZd1x7owrp3rqDa5mbn4FzlWkju+KxYUC9yTpFb//aruyO9pCp0SUd1DaaAnFLNMVmMvfq7Smc8XzG1cEDBwa1XcLCW+SPhbubUISsqOT9ABQeD0DHJJaaHHZbUY9MunSFEH3/EqRiSKxDm656Lgp1F90dMDp4/jJI5VjzUzkYwm3RoT0PzWEACRJc9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

