apiVersion: v1
kind: Namespace
metadata:
  name: cntk
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cntk-operator-group
  namespace: cntk
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - cntk
---
