apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cntk-console-link-job-sa
spec:
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
  destination:
    namespace: cntk
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cntk/console-link-job-sa
    repoURL: https://github.com/cloud-native-toolkit-test/toolkit-dev-ocp48-gitops2
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
