apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-gitops-cp-bas
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-cp-bas/namespace
    repoURL: https://github.com/cloud-native-toolkit-test/toolkit-dev-ocp48-gitops2
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
